### PR TITLE
[WIP] Easy bindings using proc macro

### PR DESCRIPTION
**Pull request by katyo**
- [x] Attribute macro `bind`
  - [x] Generating bindings
    - [x] for single functions
    - [x] for functions in modules
    - [x] for nested modules
    - [x] for class-like types (struct, enum)
    - [x] for class methods
    - [x] for static methods
    - [x] for struct fields as class properties
    - [x] for impl consts as static consts or properties
    - [x] for class constructors (`fn new()`)
  - [x] First-class support
    - [x] for async functions using promise
    - [x] for properties using getters and setters
  - [x] Supported attributes `#[quickjs(attrs...)]`
    - [x] `skip` for any entry
    - [x] `rename = "new_name"` for eny entry
    - [x] `bare` for modules
    - [x] `property` for constants
    - [x] `getter = "prop"`/`setter = "prop"` for functions and methods
    - For root module only
    - [x] `crate = "rquickjs"` to support crate renaming
    - [x] `init`/`init = "js_module_init"` to add module init function
    - [x] `module` to generate `ModuleDef` implementation
    - [x] `object` to generate `ObjectDef` implementation
- [x] Attribute macro `embed`
      This macro embeds ES6 modules by compiling it at built time.
- [x] Derive macros `FromJs` and `IntoJs`
  - [x] Struct data types
    - [x] Unit structs
    - [x] Tuple structs
    - [x] Newtype-like structs
    - [x] Structs with named fields
  - [x] Enum data types
    - [x] Unit enum variants
    - [x] Variants with discriminants
    - [x] Tuple enum variants
    - [x] Newtype-like variants
    - [x] Variants with fields
  - [x] Enum representation
    - [x] Externally tagged
    - [x] Internally tagged
    - [x] Adjacently tagged
    - [x] Untagged
  - [x] Supported attributes `#[quickjs(attrs...)]`
    - [x] `skip` for fields and variants
    - [x] `rename = "new_name"` for fields and variants
    - [x] `rename_all = "flavor"` for data type
    - [x] `crate = "rquickjs"` for data type

### CODE REVIEW

**Comment by katyo** [comment]
I experimenting with calling Rust functions from JS avoiding tuples like this:

```rust
/// The trait to wrap rust function to JS directly
pub trait AsJsFn<'js, A, R> {
    /// Minimum number of arguments
    const LEN: u32;

    /// Calling function from JS side
    fn js_call(&mut self, ctx: Ctx<'js>, args: ArgsValue<'js>) -> Result<Value<'js>>;
}

// Implementing trait for FnMut with any number of args
macro_rules! as_js_fn_impls {
    ($($($t:ident)*,)*) => {
        $(
            // Without Ctx passing
            impl<'js, F, $($t,)* R> AsJsFn<'js, ($($t,)*), R> for F
            where
                F: FnMut($($t,)*) -> R,
                $($t: FromJs<'js>,)*
                R: IntoJs<'js>,
            {
                const LEN: u32 = 0 $(+ as_js_fn_impls!(@one $t))*;

                #[allow(unused_mut, unused)]
                fn js_call(&mut self, ctx: Ctx<'js>, mut args: ArgsValue<'js>) -> Result<Value<'js>> {
                    let mut args = args.iter();
                    self($($t::from_js(ctx, args.next().ok_or_else(|| Error::Unknown)?)?,)*).into_js(ctx)
                }
            }

            // With Ctx passing
            impl<'js, F, $($t,)* R> AsJsFn<'js, (Ctx<'js>, $($t,)*), R> for F
            where
                F: FnMut(Ctx<'js>, $($t,)*) -> R,
                $($t: FromJs<'js>,)*
                R: IntoJs<'js>,
            {
                const LEN: u32 = 0 $(+ as_js_fn_impls!(@one $t))*;

                #[allow(unused_mut, unused)]
                fn js_call(&mut self, ctx: Ctx<'js>, mut args: ArgsValue<'js>) -> Result<Value<'js>> {
                    let mut args = args.iter();
                    self(ctx, $($t::from_js(ctx, args.next().ok_or_else(|| Error::Unknown)?)?,)*).into_js(ctx)
                }
            }
        )*
    };

    (@one $($t:tt)*) => { 1 };
}

as_js_fn_impls! {
    ,
    A,
    A B,
    A B C,
    ...
}
```

**Comment by katyo** [comment]
Currently a huge set of changes was applied.
Seems it's too hard to review and merge.
So I may rename my fork to publish separately.
But I don't like forks.

**Comment by katyo** [comment]
It still has a bugs related to the "parallel" feature

**Comment by DelSkayn** [comment]
> Currently a huge set of changes was applied.
> Seems it's too hard to review and merge.
> So I may rename my fork to publish separately.
> But I don't like forks.

Hey, I don't think I will be able to return to this crate any time soon.
It would indeed be unfortunate if this crate becomes one the 4 binding crates to quickjs without much development going on.
So If you are up for it I am willing to make you a contributor to this repository or transfer ownership as well as add you as owner on crates.io.
At this point some you are more invested in this crate then I am.

**Comment by katyo** [comment]
> > Currently a huge set of changes was applied.
> > Seems it's too hard to review and merge.
> > So I may rename my fork to publish separately.
> > But I don't like forks.
> 
> Hey, I don't think I will be able to return to this crate any time soon.
> It would indeed be unfortunate if this crate becomes one the 4 binding crates to quickjs without much development going on.
> So If you are up for it I am willing to make you a contributor to this repository or transfer ownership as well as add you as owner on crates.io.
> At this point some you are more invested in this crate then I am.

Sounds good to me. This crate quite near to ready for usage in production (excluding experimental features like "parallel").
I uses this bindings in my projects so I get continue developing in any case.

**Comment by katyo** [comment]
Seems mostly works.
I would like publish v0.1.0 for a new year (:

**Comment by katyo** [comment]
I plans rewrite async rt integration using hand written futures.
Seems the little bit patching of quickjs needed but it much better solution than currently implemented.

**Comment by katyo** [comment]
Seems like I done it

**Comment by DelSkayn** [comment]
> > > Currently a huge set of changes was applied.
> > > Seems it's too hard to review and merge.
> > > So I may rename my fork to publish separately.
> > > But I don't like forks.
> > 
> > 
> > Hey, I don't think I will be able to return to this crate any time soon.
> > It would indeed be unfortunate if this crate becomes one the 4 binding crates to quickjs without much development going on.
> > So If you are up for it I am willing to make you a contributor to this repository or transfer ownership as well as add you as owner on crates.io.
> > At this point some you are more invested in this crate then I am.
> 
> Sounds good to me. This crate quite near to ready for usage in production (excluding experimental features like "parallel").
> I uses this bindings in my projects so I get continue developing in any case.

Whats your username on crates.io?
then I can add you as an owner.

**Comment by katyo** [comment]
https://crates.io/users/katyo

**Comment by DelSkayn** [comment]
> 
> 
> https://crates.io/users/katyo

Alright you should have access now to both the repository as well as the crate.

**Comment by katyo** [comment]
Thanks a lot!

**Pull request merged**
