### PR TITLE
Continuous integration using GiHub actions

### PR DESCRIPTION
**Pull request by katyo**
Currently checks the following:
  - [x] Code formatting
  - [x] Docs generation
  - [x] Code lint using clippy
  - [x] Build and test for:
    - Rust channel: stable, beta, nightly
    - Target: i686, x86_64
    - Features: default, parallel, async-std, tokio
    - OSes: linux, macos, windows

  - [x] Automatic publishing by pushing new tag (using [publish-crates](/marketplace/actions/publish-crates) action)
    __NOTE__: Needs add `CRATES_TOKEN` secret.

### CODE REVIEW

**Comment by katyo** [comment]
Blocked by #14

**Comment by katyo** [comment]
Blocked by #15

**Comment by katyo** [comment]
Seems I fixed 32-bit systems support (#15)

**Comment by katyo** [comment]
Seems almost all checks pass :)
Little problem still appear with i686 linker on windows.

**Comment by katyo** [comment]
Yet another little prmlem here.
Seems bindgen cannot find rustfmt on windows, so generated bindings stay unformatted.

**Comment by katyo** [comment]
Seems this PR is ready to merge.

**Comment by katyo** [comment]
To get `publish` job working don't forget set `CRATES_TOKEN` secret for repo via settings.
See [publish-crates](https://github.com/marketplace/actions/publish-crates) action docs.

**Comment by DelSkayn** [comment]
Amazing work!

When is the publish action triggered?

**Pull request merged**
