### PR TITLE
fix: realloc rust allocator memory leak

### PR DESCRIPTION
**Pull request by richarddd**
When callculating `alloc_sice` for realloc we fail to account for the header size. This results in memory errors & leaks.
This PR fixes those issues.

### CODE REVIEW

**Review by DelSkayn — APPROVED** [review]
Yes good catch!

**Comment by Sytten** [comment]
@DelSkayn I was suggesting to @richarddd that we should try to run miri on rquickjs in CI to catch bugs in unsafe code. Thoughts?

**Comment by DelSkayn** [comment]
Miri does not work with C FFI. It is mostly for pure rust code, the moment you call out to a C function miri does not know, i.e. not a part of libc, it gives up.

**Comment by DelSkayn** [comment]
We can look into running ASAN in CI, that might work but I am not sure how to get it working on both the rust and C side.=

**Pull request merged**
